spring:
  security:
    oauth2:
      client:
        provider:
          neutron:
            issuer-uri: "http://localhost:9000"
        registration:
          neutron:
            client-id: "neutron"
            client-secret: "neutron"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
            redirect-uri: "http://localhost:5173/api/login/oauth2/code/{registrationId}"
            scope:
              - "openid"
              - "profile"
            client-name: "Neutron"
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: lb://neutron-auth
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
                - TokenRelay=
            - id: notify
              uri: lb://neutron-notify
              predicates:
                - Path=/notify/**
              filters:
                - StripPrefix=1
                - TokenRelay=