server:
  port: 9000
spring:
  application:
    name: neutron
  profiles:
    active: dev
  security:
    oauth2:
      authorizationserver:
        multiple-issuers-allowed: true
---
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false
logging:
  level:
    'io.github.hejun.neutron': debug
---
spring:
  config:
    activate:
      on-profile: prod