server:
  port: 9000
  tomcat:
    remoteip:
      protocol-header: "X-Forwarded-Proto"
spring:
  application:
    name: Neutron
  profiles:
    active: dev
  security:
    oauth2:
      authorizationserver:
        multiple-issuers-allowed: true
---
spring:
  config:
    activate:
      on-profile: dev
    import: file:neutron-server/.env.development[.yml]
logging:
  level:
    'io.github.hejun.neutron': trace
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:.env.production[.yml]
