server:
  port: 9000
spring:
  application:
    name: Neutron
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
    import: file:neutron-server/.env.development[.yml]
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:.env.production[.yml]
