server:
  port: 9000
spring:
  application:
    name: neutron
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false
---
spring:
  config:
    activate:
      on-profile: prod