/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./../src/components/layout/Aside.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    Header: typeof import('./../src/components/layout/Header.vue')['default']
    IEpHouse: typeof import('~icons/ep/house')['default']
    IEpMoonNight: typeof import('~icons/ep/moon-night')['default']
    IEpShop: typeof import('~icons/ep/shop')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const Aside: typeof import('./../src/components/layout/Aside.vue')['default']
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const Header: typeof import('./../src/components/layout/Header.vue')['default']
  const IEpHouse: typeof import('~icons/ep/house')['default']
  const IEpMoonNight: typeof import('~icons/ep/moon-night')['default']
  const IEpShop: typeof import('~icons/ep/shop')['default']
  const IEpSunny: typeof import('~icons/ep/sunny')['default']
  const IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
  const IEpUser: typeof import('~icons/ep/user')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}