name: Deploy Docs Github Pages

on:
  push:
    branches: ["master"]
    paths:
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'master'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/Jod'
      - name: Install dependencies
        run: npm install
        working-directory: docs
      - name: Build
        run: npm run docs:build
        working-directory: docs
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/.vitepress/dist'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
